### ISSUE TITLE
Download Links for Pretrained Checkpoints Not Working

### ISSUE THREAD

**Issue by jaleedkhan** [alirezazareian/gbnet#15]
The download links for the pretrained faster r-cnn checkpoint trained by [42] (https://www.dropbox.com/s/cfyqhskypu7tp0q/vg-24.tar?dl=0), and pretrained checkpoints (https://www.dropbox.com/sh/r62mzgsg1f81776/AAAQKzPD8qJrBYeYzNHJ0p5Xa?dl=0) are not working.

Can you please provide updated links to download both?

**Comment by carloscaetano** [comment]
Hi @jaleedkhan , did you manage to get those pretrained checkpoints?
